CREATE TABLE IF NOT EXISTS usuarios (
  id UUID PRIMARY KEY,
  nombre VARCHAR(120) NOT NULL,
  username VARCHAR(50) UNIQUE,
  email VARCHAR(120) UNIQUE,
  telefono VARCHAR(30) UNIQUE,
  fecha_nacimiento DATE,
  password_hash VARCHAR(255) NOT NULL,
  monedas INTEGER NOT NULL DEFAULT 0,
  puntos INTEGER NOT NULL DEFAULT 0,
  nivel_actual VARCHAR(40) NOT NULL DEFAULT 'Bronce',
  horas_streamer NUMERIC(10,2) NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS categorias (
  id SERIAL PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL UNIQUE,
  "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS regalos (
  id SERIAL PRIMARY KEY,
  nombre VARCHAR(80) NOT NULL,
  icono VARCHAR(20) NOT NULL,
  costo_monedas INTEGER NOT NULL,
  puntos_otorgados INTEGER NOT NULL,
  creado_por UUID REFERENCES usuarios(id) ON DELETE SET NULL ON UPDATE CASCADE,
  "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS streams (
  id SERIAL PRIMARY KEY,
  usuario_id UUID NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE ON UPDATE CASCADE,
  categoria_id INTEGER REFERENCES categorias(id) ON DELETE SET NULL ON UPDATE CASCADE,
  titulo VARCHAR(150) NOT NULL,
  descripcion TEXT,
  estado VARCHAR(30) NOT NULL DEFAULT 'en_vivo',
  fecha_inicio TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  fecha_fin TIMESTAMP,
  segundos_acumulados INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS mensajes_chat (
  id SERIAL PRIMARY KEY,
  stream_id INTEGER REFERENCES streams(id) ON DELETE SET NULL ON UPDATE CASCADE,
  stream_referencia VARCHAR(100) NOT NULL,
  usuario_id UUID REFERENCES usuarios(id) ON DELETE SET NULL ON UPDATE CASCADE,
  alias VARCHAR(100),
  nivel VARCHAR(40),
  texto TEXT NOT NULL,
  "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS movimientos_monedas (
  id SERIAL PRIMARY KEY,
  usuario_id UUID NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE ON UPDATE CASCADE,
  stream_id INTEGER REFERENCES streams(id) ON DELETE SET NULL ON UPDATE CASCADE,
  stream_referencia VARCHAR(100),
  regalo_id INTEGER REFERENCES regalos(id) ON DELETE SET NULL ON UPDATE CASCADE,
  tipo VARCHAR(40) NOT NULL,
  monedas INTEGER NOT NULL,
  puntos INTEGER NOT NULL DEFAULT 0,
  mensaje TEXT,
  metodo_pago VARCHAR(30),
  card_last4 VARCHAR(4),
  "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
