INSERT INTO categorias (nombre, "createdAt", "updatedAt")
VALUES
  ('Gaming', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Música', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Cocina', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Arte', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Charlando', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (nombre) DO NOTHING;

INSERT INTO regalos (nombre, icono, costo_monedas, puntos_otorgados, creado_por, "createdAt", "updatedAt")
VALUES
  ('Rosa', '🌹', 10, 5, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Corazón', '❤️', 50, 25, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Fuego', '🔥', 100, 60, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Diamante', '💎', 500, 300, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT DO NOTHING;
